name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish Nostr.Client (NuGet)
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/Nostr.Client/Nostr.Client.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: Directory.Build.props
    #- name: Publish Nostr.Client (Github)
    #  run: |
    #    dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }} --store-password-in-clear-text
    #    dotnet nuget push src/**/*.nupkg --source github --skip-duplicate
